apiVersion: v1
kind: Service
metadata:
  name: syncdoor-service
  labels:
    app: syncdoor-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31916
  selector:
    app: syncdoor
  type: NodePort
