apiVersion: v1
kind: Service
metadata:
  name: syncdoorseccon-service
  labels:
    app: syncdoorseccon-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31081
  selector:
    app: syncdoorseccon
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncdoorseccon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncdoorseccon
  template:
    metadata:
      labels:
        app: syncdoorseccon
    spec:
      containers:
        - name: syncdoorseccon
          image: napes/syncdoorseccon:v1
          args: ["http://syncdoor-service:9090/syncdoor?style=plain", "redis-service:6379", "2000", "50", ""]
          ports:
          - containerPort: 8080	  
   
